// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipCreator1.Data;

#nullable disable

namespace ShipCreator1.Migrations
{
    [DbContext(typeof(ShipCreator1Context))]
    [Migration("20250303162149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ShipCreator1.Models.ship", b =>
                {
                    b.Property<int>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NauticalMilage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PledgedFaction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShipID");

                    b.ToTable("ship");
                });
#pragma warning restore 612, 618
        }
    }
}
